export const TEXT = {
  PER_PERSON: "per person",
  INFORMATION:'Information',
  ONE_PERSON: '1 person',
  SERVICE_CHARGE: 'Service charge',
  TOTAL: 'Total',
  BOOK_NOW: 'Book now',
  FEATURED: 'Featured',
  DISCOVER: 'Discover',
  QUICK_LINKS: 'Quick Links',
  CONTACT: 'Contact',
  ADDRESS: 'Address:',
  CONTACT_CITY: 'Gurugram',
  EMAIL: 'Email:',
  EMAIL_ADDRESS: 'ayushigupta0516@gmail.com',
  PHONE: 'Phone:',
  PHONE_NUMBER: '+91 8707049776',
  MADE_WITH: 'Made with',
  IN:'in',
  JOHN_DOE: 'John Doe',
  LIA: 'Lia Franklin',
  CUSTOMER: 'Customer',
  LOGIN: 'Login',
  SIGNUP: "Signup",
  LOGOUT:  'Logout',
  LOCATION: 'Location',
  DISTANCE: 'Distance',
  MAX_PEOPLE: 'Max People',
  SUBSCRIBE_DETAILS: 'Subscribe now to get useful traveling information.',
  SUBSCRIBE: 'Subscribe',
  TRAVELING: "Traveling opens the door to creating",
  MEMORIES: 'memories',
  TRAVELING_PARA: "Traveling is an exhilarating journey that transcends boundaries, connecting us to new cultures, people, and landscapes. It's a passport to moments that awaken the soul and ignite the spirit, leaving indelible memories etched in our hearts",
  WHAT_WE_SERVE : 'What we serve',
  WE_OFFER: 'We offer our best services',
  OFFER: 'Our featured tours',
  WITH_OUR_EXPERIENCE: 'With our all experience',
  WE_WILL_SERVE_YOU:'we will serve you',
  TWELVE_K: '12k+',
  SUCCESSFUL_TRIP: 'Successful trip',
  TWO_K: '2K+',
  REGULAR_CLIENTS: 'Regular clients',
  FIFTEEN: '15',
  YEARS_EXPERIENCE: 'Years experience',
  VISIT: 'Visit our customers tour gallery',
  OUR_FANS: 'What our fans say about us',
  THANK_YOU: 'Thank you',
  BOOKED: 'Your tour is booked',
  BACK_TO_HOME: 'Back to home',
  NO_TOUR_FOUND: 'No tour found',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account? ',
  DONT_HAVE_AN_ACCOUNT: "Don't have an account?",
  CREATE: 'Create',
  SUBMIT: 'Submit',
  CAPITAL_REVIEW: 'Reviews',
  SMALL_REVIEW: 'reviews',
  DESCRIPTION: 'Description',
  PEOPLE: 'people',
  KM: 'km/hr',
  ABOUT: 'About Our Company',
  ABOUT_DESCRIPTION_ONE: "Welcome to our travel company! Explore the world with us and experience unforgettable adventures. Discover exotic destinations and create lasting memories. We offer a wide range of travel packages to suit your preferences and budget. Our team of experienced travel experts is here to assist you every step of the way. Book your dream vacation today and embark on a journey of a lifetime.",
  ABOUT_DESCRIPTION_TWO: "From the bustling streets of vibrant cities to the serene tranquility of untouched nature, travel unveils the world's kaleidoscope of experiences. Whether you seek adventure or seek solace, travel promises a tapestry of discovery that paints the canvas of our lives with vibrant colors. Join us in the pursuit of exploration, for in the world's hidden corners and well-trodden paths, there's a story waiting to be lived, and we're here to guide you on that extraordinary journey.",
  OUR_TEAM: 'Our Team',
  FOOTER_PARA: "Your adventure, your way. Customize your perfect trip with us"
};
